[functions.summarize-note]
enabled = true
verify_jwt = false
import_map = "./functions/summarize-note/deno.json"
# Entrypoint is relative to the config.toml file
entrypoint = "./functions/summarize-note/index.ts"